version: 2.1
jobs:
   build:
      machine:
          enabled: true
          image: ubuntu-2004:202107-02
      environment:
         DOCKER_BUILDKIT: 1
         COMPOSE_DOCKER_CLI_BUILD: 1
      steps:
         - checkout
         - run:
              name: docker build complete image
              command: make build
         - run:
              name: docker build and --target test
              command: make test

         - run:
              name: test Beacon-chain node docker-compose definition
              command: make test-compose-beacon

         - run:
              name: test Validator docker-compose definition
              command: make test-compose-validator

         - run:
              name: login to Dockerhub for release
              command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

         - run:
              name: push image version to Dockerhub
              command: make release

         - run:
              name: sync Dockerhub README
              command: >-
                docker run --rm -v $(pwd)/README.md:/data/README.md
                -e DOCKERHUB_USR=$DOCKER_LOGIN
                -e DOCKERHUB_PWD=$DOCKER_PWD
                -e DOCKERHUB_ORG=0labs
                -e DOCKERHUB_REPO=teku gofunky/readmyhub:stable

         - when:
              condition:
                equal: [ master, << pipeline.git.branch >> ]
              steps:
                - run:
                     name: release master version as latest
                     command: make latest
