version: "3"

networks:
  ethereum:

services:
  beacon-node:
    image: ${image:-0labs/prysm:latest}
    container_name: prysm-beacon
    command:
      - "beacon-chain"
      - "--config-file"
      - "${PRYSM_CONFIG_DIR:-/etc/prysm}/config.yml"
    environment:
      PRYSM_CONFIG_DIR:
    env_file:
      - ${beacon_env_vars:-.beacon.env}
    ports:
      - ${p2p_tcp_port:-13000}:13000/tcp
      - ${p2p_udp_port:-12000}:12000/tcp
      - ${eth2_api_port:-3501}:3501/tcp
      - ${beacon_rpc_port:-4000}:4000/tcp
      - ${beacon_metrics_port:-8080}:8080/tcp
    volumes:
      - "${host_data_dir:-/var/tmp/prysm}:${CONFIG_datadir:-/root/.eth2}"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}

  validator:
    image: ${image:-0labs/prysm:latest}
    container_name: prysm-validator
    command:
      - "validator"
      - "--config-file"
      - "${PRYSM_CONFIG_DIR:-/etc/prysm}/config.yml"
    environment:
      PRYSM_CONFIG_DIR:
    env_file:
      - ${validator_env_vars:-.validator.env}
    ports:
      - ${validator_gateway_port:-7500}:7500/tcp
      - ${validator_rpc_port:-7000}:7000/tcp
      - ${validator_metrics_port:-8081}:8081/tcp
    volumes:
      - "${host_data_dir:-/var/tmp/prysm}:${CONFIG_datadir:-/root/.eth2}"
      - "${host_wallet_dir:-/var/tmp/prysm/wallets}:/wallets"
      - "${host_keys_dir:-/var/tmp/prysm/keys}:/keys"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}
