version: "3"

networks:
  ethereum:

services:
  teku-beacon:
    image: ${image:-0labs/teku:latest}
    container_name: teku-beacon
    command:
      - "teku"
    environment:
      TEKU_CONFIG_DIR:
    env_file:
      - ${beacon_env_vars:-.beacon.env}
    ports:
      - ${p2p_tcp_port:-9000}:9000/tcp
      - ${p2p_udp_port:-9000}:9000/udp
      - ${beacon_api_port:-5051}:5051/tcp
      - ${beacon_metrics_port:-8008}:8008/tcp
    volumes:
      - "${host_data_dir:-/var/tmp/teku}:${CONFIG_datadir:-/root/.local/share/teku}"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}

  teku-validator:
    image: ${image:-0labs/teku:latest}
    container_name: teku-validator
    command:
      - "teku"
      - "validator-client"
    environment:
      PRYSM_CONFIG_DIR:
    env_file:
      - ${validator_env_vars:-.validator.env}
    ports:
      - ${validator_metrics_port:-8009}:8008/tcp
    volumes:
      - "${host_data_dir:-/var/tmp/teku}:${CONFIG_datadir:-/root/.local/share/teku}"
      - "${host_wallet_dir:-/var/tmp/teku/wallets}:/wallets"
      - "${host_keys_dir:-/var/tmp/teku/keys}:/keys"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}
