#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

if [[ "$SETUP_VALIDATOR" = "true" ]]; then
    if [ -n "${VALIDATOR_KEY+x}" ] && [ -n "${VALIDATOR_KEY_PASSWORD}" ]; then
        key_dir="${SECURITY_OUTPUT_DIR:-/var/tmp/teku}"
        mkdir -p $key_dir

        echo "${VALIDATOR_KEY}" > "${key_dir}/validator-key.json"
        echo "${VALIDATOR_KEY_PASSWORD}" > "${key_dir}/key-password.txt"
        echo "TEKU_VALIDATOR_KEYS=${key_dir}/validator-key.json:${key_dir}/key-password.txt" >> "${key_dir}/.env"
    elif [ -n "${VALIDATOR_KEYS_DIR+x}" ] && [ -n "${VALIDATOR_PWD_DIR}" ]; then
        operations_dir="${SECURITY_OUTPUT_DIR:-/var/tmp/teku}"
        mkdir -p $operations_dir

        echo "TEKU_VALIDATOR_KEYS=${VALIDATOR_KEYS_DIR}:${VALIDATOR_PWD_DIR}" >> "${operations_dir}/.env"
    fi
fi
