#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

if [[ "$SETUP_VALIDATOR" = "true" ]]; then
    if [ -n "${VALIDATOR_KEY+x}" ] && [ -n "${VALIDATOR_KEY_PASSWORD}" ]; then
        key_dir="${SECURITY_OUTPUT_DIR:-/var/tmp/teku}"
        mkdir -p $key_dir

        # if validator key is expressed as local file, use as defined; otherwise generate file accordingly
        if [[ -f "${VALIDATOR_KEY}" ]]; then
            key_file="${VALIDATOR_KEY}"
        else
            echo "${VALIDATOR_KEY}" > "${key_dir}/validator-key.json"
            key_file="${key_dir}/validator-key.json"
        fi

        # if validator password is expressed as local file, use as defined; otherwise generate file accordingly
        if [[ -f "${VALIDATOR_KEY_PASSWORD}" ]]; then
            pwd_file="${VALIDATOR_KEY_PASSWORD}"
        else
            echo "${VALIDATOR_KEY_PASSWORD}" > "${key_dir}/key-password.txt"
            pwd_file="${key_dir}/key-password.txt"
        fi
        
        echo "TEKU_VALIDATOR_KEYS=${key_file}:${pwd_file}" >> "${key_dir}/.env"
    elif [ -n "${VALIDATOR_KEYS_DIR+x}" ] && [ -n "${VALIDATOR_PWD_DIR}" ]; then
        operations_dir="${SECURITY_OUTPUT_DIR:-/var/tmp/teku}"
        mkdir -p $operations_dir

        echo "TEKU_VALIDATOR_KEYS=${VALIDATOR_KEYS_DIR}:${VALIDATOR_PWD_DIR}" >> "${operations_dir}/.env"
    fi
fi
